# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Af_Gh2gR3c5sGEyGFjAXsex2wFqdOsU6
"""

import osmnx as ox
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np





place_name = "Markham, Ontario, Canada"

graph = ox.graph_from_place(place_name)

type(graph)

fig, ax = ox.plot_graph(graph)

plt.tight_layout()

nodes, edges = ox.graph_to_gdfs(graph)



new_graph = ox.graph_from_gdfs(nodes, edges)



new_node = nodes[['x','y']]

new_node.to_csv('nodes.csv', header = True)

len(nodes)

edges.head()

edges['maxspeed']

edges['maxspeed']



new_edges = edges[['maxspeed','length']]



new_edges

new_edges.to_csv('edges.csv', header= True)

df = pd.read_csv('edges.csv')

df.head(5)

df.fillna(0, inplace = True)

df.to_csv('edges.csv', header = True)

